/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import MainPage.FirstPage;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author adity
 */
public class Admin_Login extends javax.swing.JFrame
{

    /**
     * Creates new form Admin_Login
     */
    public Admin_Login()
    {
        initComponents();
        lblForgotPassword.setVisible(false);
        btnadminLogin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblLoginTitle = new javax.swing.JLabel();
        lbladminLoginUsername = new javax.swing.JLabel();
        txtadminLoginUsername = new javax.swing.JTextField();
        lbladminLoginPassword = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        btnadminLogin = new javax.swing.JButton();
        txtadminLoginPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Login");

        lbladminLoginUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbladminLoginUsername.setForeground(new java.awt.Color(204, 204, 204));
        lbladminLoginUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbladminLoginUsername.setText("Usename :");

        txtadminLoginUsername.setBackground(new java.awt.Color(204, 204, 204));
        txtadminLoginUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtadminLoginUsername.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtadminLoginUsernameActionPerformed(evt);
            }
        });
        txtadminLoginUsername.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtadminLoginUsernameKeyTyped(evt);
            }
        });

        lbladminLoginPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbladminLoginPassword.setForeground(new java.awt.Color(204, 204, 204));
        lbladminLoginPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbladminLoginPassword.setText("Password:");

        lblForgotPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(255, 51, 51));
        lblForgotPassword.setText("Forgot  Password");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgotPassword.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblForgotPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                lblForgotPasswordMouseMoved(evt);
            }
        });
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblForgotPasswordMouseClicked(evt);
            }
        });

        btnadminLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnadminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnadminLogin.setText("Login");
        btnadminLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnadminLoginActionPerformed(evt);
            }
        });

        txtadminLoginPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtadminLoginPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtadminLoginPassword.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtadminLoginPasswordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(244, 244, 244)
                            .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbladminLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbladminLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtadminLoginUsername)
                                .addComponent(txtadminLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lblForgotPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnadminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbladminLoginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(txtadminLoginUsername))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbladminLoginPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(txtadminLoginPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnadminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtadminLoginUsernameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtadminLoginUsernameActionPerformed
    {//GEN-HEADEREND:event_txtadminLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadminLoginUsernameActionPerformed

    void clearText()
    {
        txtadminLoginUsername.setText("");
        txtadminLoginPassword.setText("");
    }

    private void btnadminLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnadminLoginActionPerformed
    {//GEN-HEADEREND:event_btnadminLoginActionPerformed
        // TODO add your handling code here:
        String name = txtadminLoginUsername.getText();
        String password = new String(txtadminLoginPassword.getPassword());
        try
        {
            Connection con = CommonFunctions.Functions.getConnection();
            String query = "SELECT * FROM admin_credentials WHERE admin_name=? AND admin_password=?";

            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, name);
            pst.setString(2, password);
            ResultSet res;
            res = pst.executeQuery();
            if (res.next())
            {
                JOptionPane.showMessageDialog(this, "Login Successfull");
                
                clearText();
                FirstPage.main(null);
                this.dispose();

            }
            else
            {
                clearText();
                JOptionPane.showMessageDialog(this, "Please enter valid credentials");
                lblForgotPassword.setVisible(true);

            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
            lblForgotPassword.setVisible(true);

        }


    }//GEN-LAST:event_btnadminLoginActionPerformed

    private void txtadminLoginUsernameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtadminLoginUsernameKeyTyped
    {//GEN-HEADEREND:event_txtadminLoginUsernameKeyTyped
        // TODO add your handling code here:
        if (txtadminLoginUsername.getText().length() != 0 && txtadminLoginPassword.getPassword().length != 0)
        {
            btnadminLogin.setEnabled(true);
        }
        else
        {
            btnadminLogin.setEnabled(false);
        }
    }//GEN-LAST:event_txtadminLoginUsernameKeyTyped

    private void txtadminLoginPasswordKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtadminLoginPasswordKeyTyped
    {//GEN-HEADEREND:event_txtadminLoginPasswordKeyTyped
        // TODO add your handling code here:
        if (txtadminLoginUsername.getText().length() != 0 && txtadminLoginPassword.getPassword().length != 0)
        {
            btnadminLogin.setEnabled(true);
        }
        else
        {
            btnadminLogin.setEnabled(false);
        }


    }//GEN-LAST:event_txtadminLoginPasswordKeyTyped

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblForgotPasswordMouseClicked
    {//GEN-HEADEREND:event_lblForgotPasswordMouseClicked
        // TODO add your handling code here:
        String id = JOptionPane.showInputDialog("Enter your Id number :");

        try
        {
            int userid = Integer.parseInt(id);
            if (id == null || id.length() == 0)
            {
                throw new Exception();
            }

            String query = "SELECT * FROM admin_credentials WHERE adminId =?";
            try
            {
              
                Connection con = CommonFunctions.Functions.getConnection();
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, id);

                ResultSet rst = pst.executeQuery();
                if (rst.next())
                {
                    JOptionPane.showMessageDialog(this, "Your Password is : " + rst.getString("admin_password"));
                    clearText();
                    lblForgotPassword.setVisible(false);

                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sorry , User not found. Please check your Id.", "Forgot Password", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Please Enter valid Id number", "Forgot Password", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }


    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    private void lblForgotPasswordMouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblForgotPasswordMouseMoved
    {//GEN-HEADEREND:event_lblForgotPasswordMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblForgotPasswordMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Admin_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Admin_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadminLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lbladminLoginPassword;
    private javax.swing.JLabel lbladminLoginUsername;
    private javax.swing.JPasswordField txtadminLoginPassword;
    private javax.swing.JTextField txtadminLoginUsername;
    // End of variables declaration//GEN-END:variables
}
