/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student_form;

import MainPage.ImageCapture;
import java.awt.HeadlessException;
import java.awt.ImageCapabilities;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author adity
 */
public class Registration extends javax.swing.JFrame
{

    /**
     * Creates new form Registration
     */
    public Registration()
    {
        initComponents();
        btnSubmit.setEnabled(false);
        setComboCollege();
        combCollege.setSelectedIndex(-1);
        setHometown();
        combHometown.setSelectedIndex(-1);
    }

    private void setComboCollege()
    {
        combCollege.removeAllItems();

        try
        {
            Connection con = CommonFunctions.Functions.getConnection();
            String q = "SELECT * FROM college order by college_id";
            PreparedStatement st = con.prepareStatement(q);

            ResultSet rs = st.executeQuery();

            while (rs.next())
            {
                combCollege.addItem(rs.getString("college_name"));
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);

        }

    }

  public void setHometown()
    {
        combHometown.removeAllItems();
        try
        {
            Connection con = CommonFunctions.Functions.getConnection();
            String q = "SELECT * FROM hometown ORDER BY hometown_id";
            PreparedStatement st = con.prepareStatement(q);

            ResultSet rs = st.executeQuery();

            while (rs.next())
            {
                combHometown.addItem(rs.getString("hometown_name"));
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlRegistrationMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlInfo1 = new javax.swing.JPanel();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        lblMname = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        dBirthdate = new com.toedter.calendar.JDateChooser();
        lblLname2 = new javax.swing.JLabel();
        pnlInfo2 = new javax.swing.JPanel();
        lblFname1 = new javax.swing.JLabel();
        txtLaddress = new javax.swing.JTextField();
        txtPaddress = new javax.swing.JTextField();
        lblLname1 = new javax.swing.JLabel();
        combCollege = new javax.swing.JComboBox<>();
        lblFname2 = new javax.swing.JLabel();
        combHometown = new javax.swing.JComboBox<>();
        lblFname3 = new javax.swing.JLabel();
        btnAddHometown = new javax.swing.JButton();
        btnAddCollege = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblLaddress = new javax.swing.JLabel();
        lblPaddress = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chkC = new javax.swing.JCheckBox();
        chkCpp = new javax.swing.JCheckBox();
        chkJava = new javax.swing.JCheckBox();
        chkJDsa = new javax.swing.JCheckBox();
        chkJAds = new javax.swing.JCheckBox();
        btnImageCap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlRegistrationMain.setBackground(new java.awt.Color(102, 102, 102));
        pnlRegistrationMain.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Registration");

        pnlInfo1.setBackground(new java.awt.Color(153, 153, 153));
        pnlInfo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.gray));

        lblFname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFname.setText("First name :");

        txtFname.setBackground(new java.awt.Color(204, 204, 204));
        txtFname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFnameActionPerformed(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtFnameKeyTyped(evt);
            }
        });

        txtMname.setBackground(new java.awt.Color(204, 204, 204));
        txtMname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtMnameActionPerformed(evt);
            }
        });
        txtMname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtMnameKeyTyped(evt);
            }
        });

        lblMname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMname.setText("Middle name :");

        txtLname.setBackground(new java.awt.Color(204, 204, 204));
        txtLname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtLnameActionPerformed(evt);
            }
        });

        lblLname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLname.setText("Last name :");
        lblLname.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                lblLnameKeyTyped(evt);
            }
        });

        txtPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtPhoneKeyTyped(evt);
            }
        });

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone :");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtEmailActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmail.setText("Email :");

        lblLname2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLname2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLname2.setText("Birth Date :");

        javax.swing.GroupLayout pnlInfo1Layout = new javax.swing.GroupLayout(pnlInfo1);
        pnlInfo1.setLayout(pnlInfo1Layout);
        pnlInfo1Layout.setHorizontalGroup(
            pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfo1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFname)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhone)
                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlInfo1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(pnlInfo1Layout.createSequentialGroup()
                        .addComponent(lblMname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dBirthdate, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtLname))
                .addGap(24, 24, 24))
        );
        pnlInfo1Layout.setVerticalGroup(
            pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfo1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfo1Layout.createSequentialGroup()
                        .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLname2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dBirthdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(pnlInfo1Layout.createSequentialGroup()
                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlInfo2.setBackground(new java.awt.Color(153, 153, 153));
        pnlInfo2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.gray));

        lblFname1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFname1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFname1.setText("Local Adddress :");

        txtLaddress.setBackground(new java.awt.Color(204, 204, 204));
        txtLaddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLaddress.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtLaddressActionPerformed(evt);
            }
        });

        txtPaddress.setBackground(new java.awt.Color(204, 204, 204));
        txtPaddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPaddress.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPaddressActionPerformed(evt);
            }
        });

        lblLname1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLname1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLname1.setText("Permenant Address :");

        combCollege.setBackground(new java.awt.Color(102, 102, 102));
        combCollege.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combCollege.setForeground(new java.awt.Color(153, 153, 153));
        combCollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combCollege.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                combCollegeActionPerformed(evt);
            }
        });

        lblFname2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFname2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFname2.setText("College :");

        combHometown.setBackground(new java.awt.Color(102, 102, 102));
        combHometown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combHometown.setForeground(new java.awt.Color(153, 153, 153));
        combHometown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combHometown.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                combHometownActionPerformed(evt);
            }
        });

        lblFname3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFname3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFname3.setText("Home Town :");

        btnAddHometown.setBackground(new java.awt.Color(204, 204, 204));
        btnAddHometown.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddHometown.setText("+");
        btnAddHometown.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddHometownActionPerformed(evt);
            }
        });

        btnAddCollege.setBackground(new java.awt.Color(204, 204, 204));
        btnAddCollege.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddCollege.setText("+");
        btnAddCollege.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddCollegeActionPerformed(evt);
            }
        });

        jButton1.setText("=>");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<=");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        lblLaddress.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblLaddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLaddress.setText("Clear");
        lblLaddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLaddress.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblLaddressMouseClicked(evt);
            }
        });

        lblPaddress.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPaddress.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPaddress.setText("Clear");
        lblPaddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPaddress.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblPaddressMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlInfo2Layout = new javax.swing.GroupLayout(pnlInfo2);
        pnlInfo2.setLayout(pnlInfo2Layout);
        pnlInfo2Layout.setHorizontalGroup(
            pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfo2Layout.createSequentialGroup()
                .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInfo2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInfo2Layout.createSequentialGroup()
                        .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfo2Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lblFname2)
                                .addGap(18, 18, 18)
                                .addComponent(combCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlInfo2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblLaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInfo2Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(lblFname1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfo2Layout.createSequentialGroup()
                                .addComponent(lblLname1)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfo2Layout.createSequentialGroup()
                                .addComponent(lblFname3)
                                .addGap(18, 18, 18)
                                .addComponent(combHometown, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddHometown, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        pnlInfo2Layout.setVerticalGroup(
            pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfo2Layout.createSequentialGroup()
                .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfo2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddHometown, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFname3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combHometown, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInfo2Layout.createSequentialGroup()
                        .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfo2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLname1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFname1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLaddress)
                                    .addComponent(lblPaddress)))
                            .addGroup(pnlInfo2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFname2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        btnSubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Languages Inteasted :");

        chkC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkC.setText("C");
        chkC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkCActionPerformed(evt);
            }
        });

        chkCpp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCpp.setText("C++");

        chkJava.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkJava.setText("JAVA");

        chkJDsa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkJDsa.setText("DSA");
        chkJDsa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkJDsaActionPerformed(evt);
            }
        });

        chkJAds.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkJAds.setText("ADS");
        chkJAds.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkJAdsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(chkC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(chkCpp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(chkJava, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(chkJDsa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(chkJAds, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkCpp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkJava, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkJDsa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkJAds, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );

        btnImageCap.setText("Capture");
        btnImageCap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnImageCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrationMainLayout = new javax.swing.GroupLayout(pnlRegistrationMain);
        pnlRegistrationMain.setLayout(pnlRegistrationMainLayout);
        pnlRegistrationMainLayout.setHorizontalGroup(
            pnlRegistrationMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationMainLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRegistrationMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistrationMainLayout.createSequentialGroup()
                        .addComponent(btnImageCap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(715, 715, 715)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistrationMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlInfo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlRegistrationMainLayout.setVerticalGroup(
            pnlRegistrationMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrationMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(pnlInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pnlInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistrationMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImageCap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistrationMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistrationMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1059, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFnameActionPerformed
    {//GEN-HEADEREND:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtMnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtMnameActionPerformed
    {//GEN-HEADEREND:event_txtMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtLnameActionPerformed
    {//GEN-HEADEREND:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPhoneActionPerformed
    {//GEN-HEADEREND:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtEmailActionPerformed
    {//GEN-HEADEREND:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPaddressActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPaddressActionPerformed
    {//GEN-HEADEREND:event_txtPaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaddressActionPerformed

    private void txtLaddressActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtLaddressActionPerformed
    {//GEN-HEADEREND:event_txtLaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLaddressActionPerformed

    private void combCollegeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_combCollegeActionPerformed
    {//GEN-HEADEREND:event_combCollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combCollegeActionPerformed

    private void combHometownActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_combHometownActionPerformed
    {//GEN-HEADEREND:event_combHometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combHometownActionPerformed

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtPhoneKeyTyped
    {//GEN-HEADEREND:event_txtPhoneKeyTyped
        // TODO add your handling code here:

        char ch = evt.getKeyChar();

        if (Character.isAlphabetic(ch))
        {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Please enter digits only", "Phone number ", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if (txtPhone.getText().length() > 10)
            {
                JOptionPane.showMessageDialog(this, "Please enter Valid Phone number", "Phone number ", JOptionPane.ERROR_MESSAGE);
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void txtFnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFnameKeyTyped
    {//GEN-HEADEREND:event_txtFnameKeyTyped
        char ch = evt.getKeyChar();

        if (Character.isDigit(ch))
        {
            evt.consume();

        }

        btnSubmit.setEnabled(canSubmit());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameKeyTyped

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSubmitActionPerformed
    {//GEN-HEADEREND:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String fname, lname, mname, phone, email;
        java.util.Date bdate, edate;
        java.sql.Date birth;
        String laddress, paddress, college, hometown;

        String lang;

        fname = txtFname.getText().trim();
        mname = txtMname.getText().trim();
        lname = txtLname.getText().trim();
        phone = txtPhone.getText().trim();
        email = txtEmail.getText().trim();
        laddress = txtLaddress.getText().trim();
        paddress = txtPaddress.getText().trim();
        bdate = dBirthdate.getDate();
        SimpleDateFormat d = new SimpleDateFormat("YYYY-MM-dd");
        // birth date 
        String dte = d.format(bdate);

        edate = new java.util.Date();
        SimpleDateFormat de = new SimpleDateFormat("YYYY-MM-dd");
         // enq date 
        String se = de.format(edate);
        
        
        
        
        try
        {
            Connection con = CommonFunctions.Functions.getConnection();
            String s = "SELECT max(student_id) AS student FROM student";
            PreparedStatement st = con.prepareStatement(s);
            
            ResultSet r = st.executeQuery();
            int id = 1;
            if(r.next())
            {
              //  System.out.println("=="+r.getString("student"));
                id = Integer.parseInt(r.getString("student"));
                id++;
                if(r.getString("student")==null)id=1;
            }
            
            
            
              FileInputStream fn = new FileInputStream("C:\\Users\\adity\\OneDrive\\Documents\\NetBeansProjects\\Student_Registration_System\\src\\Images\\img.jpeg");
     
            
            String q = "INSERT INTO student(student_id,hometown_id,college_id,fname,mname,lname,phone,email,image,address_local,address_permanant,birth_date) Values (?,?,?,?,?,?,?,?,?,?,?,?)";
             
            PreparedStatement prt = con.prepareStatement(q);
            prt.setInt(1, id);
            prt.setInt(2, combHometown.getSelectedIndex()+1);
            prt.setInt(3,combCollege.getSelectedIndex()+1);
            prt.setString(4, fname);
            prt.setString(5, mname);
            prt.setString(6, lname);
            prt.setString(7, phone);
            prt.setString(8, email);
            prt.setBlob(9, fn);
            prt.setString(10, laddress);
            prt.setString(11,paddress);
            prt.setString(12,dte);
            prt.executeUpdate();
            
          
            JOptionPane.showMessageDialog(this, " registered successsfully , Student ID  : "+id);
            
            // adding enquiry info 
            
            String subs="";
            if(chkC.isSelected())
            {
                subs+=chkC.getText()+',';
            }
            
             if(chkCpp.isSelected())
            {
                subs+=chkCpp.getText()+',';
            }
            
             if(chkJava.isSelected())
            {
                subs+=chkJava.getText()+',';
            }
            
              if(chkJDsa.isSelected())
            {
                subs+=chkJDsa.getText()+',';
            }
             
              
               if(chkJAds.isSelected())
            {
                subs+=chkJAds.getText();
            }
            
               subs.trim();
            String enq = "INSERT INTO enquiry(student_id,college_id,hometown_id,subject_intreasted,enquiry_date) VALUES(?,?,?,?,?) ";

            PreparedStatement enp = con.prepareStatement(enq);
            enp.setInt(1,id);
            enp.setInt(2, combCollege.getSelectedIndex()+1);
            enp.setInt(3, combHometown.getSelectedIndex()+1);
            enp.setString(4, subs);
            enp.setString(5, se);
            
            enp.executeUpdate();
            System.out.println("enquired");
            
        }
        catch (HeadlessException | FileNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this, e);
                    
        }
       
           
        
        
       
      
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtMnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtMnameKeyTyped
    {//GEN-HEADEREND:event_txtMnameKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();

        if (Character.isDigit(ch))
        {
            evt.consume();
        }

        btnSubmit.setEnabled(canSubmit());
    }//GEN-LAST:event_txtMnameKeyTyped

    private void lblLnameKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_lblLnameKeyTyped
    {//GEN-HEADEREND:event_lblLnameKeyTyped

        char ch = evt.getKeyChar();

        if (Character.isDigit(ch))
        {
            evt.consume();

        }
        btnSubmit.setEnabled(canSubmit());

        // TODO add your handling code here:
    }//GEN-LAST:event_lblLnameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String Laddress = txtLaddress.getText();

        txtPaddress.setText(Laddress);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String La = txtLaddress.getText();
        String pa = txtPaddress.getText();
        if (!La.equals(pa))
        {
            txtPaddress.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblLaddressMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblLaddressMouseClicked
    {//GEN-HEADEREND:event_lblLaddressMouseClicked
        // TODO add your handling code here:
        txtLaddress.setText("");
    }//GEN-LAST:event_lblLaddressMouseClicked

    private void lblPaddressMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblPaddressMouseClicked
    {//GEN-HEADEREND:event_lblPaddressMouseClicked
        // TODO add your handling code here:
        txtPaddress.setText("");
    }//GEN-LAST:event_lblPaddressMouseClicked

    private void btnAddCollegeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddCollegeActionPerformed
    {//GEN-HEADEREND:event_btnAddCollegeActionPerformed
        // TODO add your handling code here:
        String Str = "";
        try
        {
            Str = JOptionPane.showInputDialog("Please Enter college name : ");

        }
        catch (Exception w)
        {

        }

        try
        {
            Connection con = CommonFunctions.Functions.getConnection();
            String s = "SELECT * FROM college  WHERE college_name=?";
            PreparedStatement st = con.prepareStatement(s);
            st.setString(1, Str);

            ResultSet r = st.executeQuery();

            if (r.next())
            {
                combCollege.setSelectedIndex(Integer.parseInt(r.getString("college_id")) - 1);
            }
            else
            {
                s = "INSERT INTO college(college_name) Values(?)";
                st = con.prepareStatement(s);
                st.setString(1, Str);
                st.executeUpdate();
                setComboCollege();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_btnAddCollegeActionPerformed

    private void btnAddHometownActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddHometownActionPerformed
    {//GEN-HEADEREND:event_btnAddHometownActionPerformed
        // TODO add your handling code here:

   
      

        try
        {
              String   Str = JOptionPane.showInputDialog("Please Enter Home Town: ");
            Connection con = CommonFunctions.Functions.getConnection();
            String s = "SELECT * FROM hometown  WHERE hometown_name=?";
            PreparedStatement st = con.prepareStatement(s);
            st.setString(1, Str);

            ResultSet r = st.executeQuery();

            if (r.next())
            {
                combHometown.setSelectedIndex(Integer.parseInt(r.getString("hometown_id")) - 1);
            }
            else
            {
                s = "INSERT INTO hometown(hometown_name) Values(?)";
                st = con.prepareStatement(s);
                st.setString(1, Str);
                st.executeUpdate();
                setHometown();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }

        
    }//GEN-LAST:event_btnAddHometownActionPerformed

    private void chkCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkCActionPerformed
    {//GEN-HEADEREND:event_chkCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCActionPerformed

    private void chkJDsaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkJDsaActionPerformed
    {//GEN-HEADEREND:event_chkJDsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJDsaActionPerformed

    private void chkJAdsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkJAdsActionPerformed
    {//GEN-HEADEREND:event_chkJAdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJAdsActionPerformed

    private void btnImageCapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnImageCapActionPerformed
    {//GEN-HEADEREND:event_btnImageCapActionPerformed
        // TODO add your handling code here:
                ImageCapture.main(null);
    }//GEN-LAST:event_btnImageCapActionPerformed

    public boolean canSubmit()
    {
        if (txtFname.getText().length() == 0 || txtLname.getText().length() == 0 || txtFname.getText().length() == 0 || txtPhone.getText().length() == 0 || txtEmail.getText().length() == 0)
        {
            return (false);
        }
        else
        {
            return (true);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCollege;
    private javax.swing.JButton btnAddHometown;
    private javax.swing.JButton btnImageCap;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkC;
    private javax.swing.JCheckBox chkCpp;
    private javax.swing.JCheckBox chkJAds;
    private javax.swing.JCheckBox chkJDsa;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JComboBox<String> combCollege;
    private javax.swing.JComboBox<String> combHometown;
    private com.toedter.calendar.JDateChooser dBirthdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblFname1;
    private javax.swing.JLabel lblFname2;
    private javax.swing.JLabel lblFname3;
    private javax.swing.JLabel lblLaddress;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblLname1;
    private javax.swing.JLabel lblLname2;
    private javax.swing.JLabel lblMname;
    private javax.swing.JLabel lblPaddress;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JPanel pnlInfo1;
    private javax.swing.JPanel pnlInfo2;
    private javax.swing.JPanel pnlRegistrationMain;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLaddress;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtPaddress;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
